# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://matematikfessor.dk/")
    self.driver.set_window_size(1324, 1457)
    self.driver.find_element(By.ID, "topLoginEmailButton").click()
    element = self.driver.find_element(By.ID, "topLoginEmailButton")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".content > #emailLoginTop #TopLoginEmail").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content > #emailLoginTop #TopLoginEmail").send_keys("dicexem843@anlubi.com")
    self.driver.find_element(By.CSS_SELECTOR, ".content > #emailLoginTop #TopLoginPassword").click()
    self.driver.find_element(By.CSS_SELECTOR, ".content > #emailLoginTop #TopLoginPassword").send_keys("sgkA54Kfdg")
    self.driver.find_element(By.CSS_SELECTOR, ".content > #emailLoginTop .cssButton").click()
    element = self.driver.find_element(By.LINK_TEXT, "Hjælp")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
  
